name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Read .hugoversion
      id: hugo-version
      run: |
        hv=$(cat .hugoversion)
        echo "HUGO_VERSION=${hv#v*}" >> $GITHUB_OUTPUT

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@32c7754570a8edd0ae33352fae4a8448f23858e9 # v3.1.0
      with:
        hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
        extended: true

    - name: Build
      run: ./build.sh
